flowchart LR
    E["OS_Graphical_System"] -- "System_Changing_Theme" --> A["Electron_Frontend"]
    A["Electron_Frontend"] -- "User_Queries" --> B{"Monolithic Backend"}
    B -- "Execute_Queries" --> C{"MongoDB Database"}
    C -- "Return_Data" --> B
    B -- "JSON_Results" --> A
    A <-- "Settings" --> B
    A <-- "Query_History" --> B
    B -- "Persistent Storage for Settings & History" --> D["Local_Storage"]
